### ISSUE TITLE
ISOSTS DTD validation error on Rice document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2sts#13]
```
Input: XML (documents/iso-rice-en.cd.sts.xml)

Validate XML againts DTD ISO-STS-DTD_v1.1/ISOSTS.dtd...
/Users/mulgogi/src/mn/mn2sts/documents/iso-rice-en.cd.sts.xml is NOT valid reason:
[ERROR] org.xml.sax.SAXParseException; lineNumber: 1673; columnNumber: 7; Element type "code" must be declared.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 1677; columnNumber: 56; Attribute "id" must be declared for element type "annotation".
[ERROR] org.xml.sax.SAXParseException; lineNumber: 1683; columnNumber: 25; The content of element type "non-normative-example" must match "(label?,(address|alternatives|array|boxed-text|chem-struct-wrap|fig|fig-group|graphic|media|non-normative-note|non-normative-example|preformat|supplementary-material|table-wrap|table-wrap-group|disp-formula|disp-formula-group|p|def-list|list|mml:math|related-article|related-object|disp-quote|speech|statement|verse-group)*)".
[ERROR] org.xml.sax.SAXParseException; lineNumber: 1799; columnNumber: 12; An element with the identifier "_bbe86fa2-4f7d-44f8-922e-0679614c87d4" must appear in the document.
End!
```

**Comment by Intelligent2013** [comment]
These errors are limitation of STS **ISO** DTD.

Source MN XML rice-en.cd.xml contains element `sourcecode`:
```xml
<appendix id="_sample_code" inline-header="false" obligation="informative">
	<title>Sample code</title>
	<example id="samplecode">
		<name>Sample Code</name>
		<sourcecode lang="ruby" id="_6e938028-db97-4536-b3aa-81e4dcd2b5f3">puts "Hello, world."
%w{a b c}.each do |x| <callout target="_bbe86fa2-4f7d-44f8-922e-0679614c87d4">1</callout>
  puts x
end<annotation id="_bbe86fa2-4f7d-44f8-922e-0679614c87d4">
				<p id="_7048af06-f6a4-4dc5-bd57-0918faf08b8d">This is an annotation</p>
			</annotation>
		</sourcecode>
	</example>
</appendix>
```

I convert it to STS **NISO** element `code`:
```xml
<sec id="_sample_code">
	<title>Sample code</title>
	<non-normative-example>
		<label>EXAMPLE</label>
		<code>puts "Hello, world."
%w{a b c}.each do |x| <xref rid="_bbe86fa2-4f7d-44f8-922e-0679614c87d4" ref-type="other">1</xref>
  puts x
end<element-citation>
				<annotation id="_bbe86fa2-4f7d-44f8-922e-0679614c87d4">
					<p>This is an annotation</p>
				</annotation>
			</element-citation>
		</code>
	</non-normative-example>
</sec>
```

Errors mean:
-  `Element type "code" must be declared.` - STS DTD **ISO** doesn't contain such element 'code' at all. (But STS DTD **NISO** contains).
- `Attribute "id" must be declared for element type "annotation".` - STS DTD ISO doesn't contain @id
- `The content of element type "non-normative-example" must match "(label?,(address|alternatives|array|boxed-text|chem-struct-wrap|fig|fig-group|graphic|media|non-normative-note|non-normative-example|preformat|supplementary-material|table-wrap|table-wrap-group|disp-formula|disp-formula-group|p|def-list|list|mml:math|related-article|related-object|disp-quote|speech|statement|verse-group)*)".` - `non-normative-example` doesn't contain `code`, because it doesn't declared.
- `An element with the identifier "_bbe86fa2-4f7d-44f8-922e-0679614c87d4" must appear in the document.` - this is link between `xref` and `annotation` inside `code`. `xref` 'doesn't see' `annotation/@id` becaise it doesn't declared in dtd.

**Comment by Intelligent2013** [comment]
@ronaldtse I propose to close it, because validation errors relate to ISO DTD (not NISO) due the restrictions in DTD.

**Comment by ronaldtse** [comment]
I have a question -- we need to provide ISOSTS output. What can we do here? Separate two types of outputs?

**Comment by Intelligent2013** [comment]
> 
> 
> I have a question -- we need to provide ISOSTS output. What can we do here? Separate two types of outputs?

XSLT was developed to produce NISO STS. We can adopt it to produce both NISO STS and restricted ISO STS, by selecting output format in mn2sts command line. Then I need to check gaps between NISO and ISO xmls.

**Comment by Intelligent2013** [comment]
Done. [mn2sts-1.5.jar](https://github.com/metanorma/mn2sts/releases/tag/v1.5)
```
Input: XML (documents/iso-rice-en.cd.sts.xml)

Validate XML againts DTD ISO-STS-DTD_v1.1/ISOSTS.dtd...
/home/runner/work/mn2sts/mn2sts/documents/iso-rice-en.cd.sts.xml is valid.
End!
```

**Comment by ronaldtse** [comment]
@Intelligent2013 thanks! How does @opoudjis enable ISOSTS output?

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 thanks! How does @opoudjis enable ISOSTS output?

Add command line parameter `--output-format iso`:
```sh
java -jar mn2sts.jar --xml-file-in input.mn.xml --xml-file-out output.sts.xml --output-format iso
```

**Comment by opoudjis** [comment]
You have both forgotten to update the jar file in https://github.com/metanorma/mn2sts-ruby/tree/master/bin, which is what Metanorma actually uses.

**Comment by opoudjis** [comment]
@Intelligent2013 For future releases, please inform me so I can update mn2sts-ruby. It has not been updated in the past three months.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 For future releases, please inform me so I can update mn2sts-ruby. It has not been updated in the past three months.

@opoudjis ok.

**Comment by ronaldtse** [comment]
I think it’s supposed to be automatically created by the GHA. Ping @CAMOBAP 

Posted here: https://github.com/metanorma/mn2sts-ruby/issues/3

**Comment by Intelligent2013** [comment]
Closing. All done a long ago.
