### ISSUE TITLE
MN to NISO: quote element

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2sts#9]
@ronaldtse
The source xml (https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-en.final.xml) contains `quote` element:
```
<quote id="_dd430fae-3500-43b9-a899-34125bf21700">
<source type="inline" bibitemid="ISO7301" citeas="ISO 7301:2011"><localityStack><locality type="clause"><referenceFrom>1</referenceFrom></locality></localityStack></source>
<author>ISO</author>
<p id="_fdbc9772-96c3-43ff-8e2b-59ea33ae41c6">This International Standard gives the minimum specifications for rice (<em>Oryza sativa</em> L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).</p>
</quote>
```
It displays as:
![изображение](https://user-images.githubusercontent.com/5559926/83285235-95714580-a1e6-11ea-83d4-907c0ff213fd.png)

It seems in NISO there is a similar element `disp-quote`, but I don't sure that it fits for this purpose, because there aren't elements for `author` and `source`.

**Comment by ronaldtse** [comment]
Ping @opoudjis for an answer.

**Comment by opoudjis** [comment]
The citation for the quote goes into `<related-object>`

The author becomes either `disp-quote/related-object/collab` or `disp-quote/related-object/string-name`, depending on whether they are a person or an organisation. We don't have enough information to break the source down into a bibliographic record, so it simply becomes the remainder of the content of `disp-quote/related-object`. In fact, since we don't know what the status of the author is, it's best just to dump author + source into the text of related-object, which is permitted. That means rendering the localityStack as text.

So:

````
<disp-quote id="_dd430fae-3500-43b9-a899-34125bf21700">
<p id="_fdbc9772-96c3-43ff-8e2b-59ea33ae41c6">This International Standard gives the minimum specifications for rice (<em>Oryza sativa</em> L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).</p>
<related-object>
ISO, ISO 7301:2011, Clause 1
</related-object>
</disp-quote>
````

We simply don't have the information to generate a semantically tagged reference:

````
<related-object document-id="ISO 7301:2011">
<collab>ISO</collab>, <chapter-title>Clause 1</chapter-title>
</related-object>
````

or 

````
<related-object>
<std std-id="ISO 7301:2011">
<collab>ISO</collab> <std-ref>ISO 7301:2011</std-ref> Clause 1
</std>
</related-object>
````

**Comment by ronaldtse** [comment]
Thanks @opoudjis for the answer but please don't close it since it is actionable for @Intelligent2013

**Comment by Intelligent2013** [comment]
@opoudjis thank you!
